spring.application.name=bulletin

# PostgreSQL 연결
spring.datasource.url=jdbc:postgresql://localhost:5432/bulletin_board
spring.datasource.username=postgres
spring.datasource.password=000622
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT 설정
jwt.secret=jungle-bulletin-secret-key-must-be-at-least-32-characters-long
jwt.expiration=86400000